### ISSUE TITLE
Dependancy Issue.

### ISSUE THREAD

**Issue by vatsal1992** [liufengting/FTImageViewer#1]
when i integrate using cocoa pods. it download AlamofireImage also. and in your Example you are using Kingfisher. please update cocoa pod.

**Comment by liufengting** [comment]
I am having the issue. I'm not able to upload it to Cocoapods using Swift 3.0. I have been trying many times until now, still failing. Please checkout the code from master branch, and use 'Kingfisher' in your Podfile. Once I uploaded, I will let you know. Sorry for the inconvenience.

**Comment by vatsal1992** [comment]
thanks for reply, but i've to say that the example you provided is actually helpful and useful. +1 for your efforts.

**Comment by liufengting** [comment]
I just upload it to cococapods, the current version is 1.9.5.
