### ISSUE TITLE
网页的图浏览如何使用呢？

### ISSUE THREAD

**Issue by Yesi-hoang** [liufengting/FTImageViewer#2]
请问下网页的图可以用吗？可以获取到images 的urls  但是没办法设置像你demo的FTImageGridView容器视图？

**Comment by liufengting** [comment]
稍等，我试试

**Comment by Yesi-hoang** [comment]
好的😀

**Comment by liufengting** [comment]
最新提交的代码demo里有。只是我没有办法获取imageview，还在找。。


![1111111](https://cloud.githubusercontent.com/assets/4414522/20471202/a4aed87e-afea-11e6-9117-8361b88f85b4.png)

**Comment by liufengting** [comment]
另外，版本还有点问题，我稍后会重新提交pod版本上去。

**Comment by Yesi-hoang** [comment]
好的
