### ISSUE TITLE
FTImageViewer doesn't work when rotating is enabled

### ISSUE THREAD

**Issue by jackbravo** [liufengting/FTImageViewer#5]
To fix this I think that we need to replace FTImageViewerScreenWidth and FTImageViewerScreenHeight variables with UIScreen.main.bounds. This solves the issue when rotating and launching a new FTImageViewer, but not when rotating while using the FTImageViewer.

**Comment by liufengting** [comment]
I will try fix this very soon.

**Comment by liufengting** [comment]
I just add rotating support. V1.9.9 is available today.

**Comment by jackbravo** [comment]
Works like a charm.
